#!/bin/sh

shout() { echo "$0: $*" >&2; }  # Just echo an error and the program name
barf() { shout "$*"; exit 111; }
safe() { "$@" || barf "cannot $*"; }

# =============================================================================
# Post-install hook file for configuring dotcloud server

echo "Writing the local settings file..."
cat >> src/project/local_settings.py <<EOF

import json
with open('/home/dotcloud/environment.json') as f:
    env = json.load(f)

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'shareabouts',
        'USER': env['DOTCLOUD_DB_SQL_LOGIN'],
        'PASSWORD': env['DOTCLOUD_DB_SQL_PASSWORD'],
        'HOST': env['DOTCLOUD_DB_SQL_HOST'],
        'PORT': int(env['DOTCLOUD_DB_SQL_PORT']),
    }
}

STATIC_ROOT = '/home/dotcloud/current/static/'

EOF

# Need to be able to import settings to run the createdbs script...
echo VIRTUAL_ENV is "$VIRTUAL_ENV"
echo PYTHONPATH is "$PYTHONPATH"
export PYTHONPATH=$PYTHONPATH:$PWD/src/
export DJANGO_SETTINGS_MODULE=project.settings
echo "Creating database if needed..."
safe python src/scripts/dotcloud_createdbs.py

echo "Syncing the database..."
safe src/manage.py syncdb --migrate --noinput

echo "Setting up static file service..."
safe src/manage.py collectstatic --noinput

echo "Configuring nginx to serve static files..."
cat >> nginx.conf <<EOF
location /static/ { root /home/dotcloud/current ; }
EOF

