#!/usr/bin/env ruby
# This command will generate ActivityItems for all FeaturePoints, Votes,
# and Comments in the database.

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))

all = []

FeaturePoint.visible.find_in_batches do |batch|
  all += batch
end

Vote.find_in_batches do |batch|
  all += batch
end

Comment.find_in_batches do |batch|
  all += batch
end

all.sort! {|a,b| a.created_at <=> b.created_at }

all.each do |observed|
  parent = if observed.respond_to?(:commentable)
    observed.commentable
  elsif observed.respond_to?(:supportable)
    observed.supportable
  end
  
  ActivityItem.create({
    :subject        => observed, 
    :user           => observed.user,
    :user_name      => observed.user.try(:name),
    :subject_parent => parent
  }) unless ActivityItem.where(:subject_id => observed.id, :subject_type => observed.class.to_s).exists?
end
