#!/usr/bin/env ruby
# This command will populate the location_type table with values from db/seeds/cb7_locationtypes.csv

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))

CSV.foreach( File.join(Rails.root,'db','seeds','cb7_locationtypes.csv'), headers: true ) do |r|
  loctype = LocationType.find_or_create_by_name(r['location_type'])
end

puts "#{LocationType.count} location types"
