#!/usr/bin/env ruby
# This command will populate the location_type table with values from db/seeds/cb7_locationtypes.csv

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))

data = YAML.load_file( File.join(Rails.root,'db','seeds','cb7_pages.yml'))
pages = data['pages']
pages.each do |slug,params|
  page = Page.find_or_create_by_slug(slug)
  params.each do |name,value|
    page.instance_variable_set("@#{name}", value)
  end
  page.save
end

puts "#{Page.count} pages"
