#!/usr/bin/env python

from __future__ import unicode_literals, print_function

import os
import psycopg2
import subprocess

dburl = os.environ.get('DATABASE_URL')

print('Connecting to the database...', end='')
conn = psycopg2.connect(dburl)
cur = conn.cursor()
print('done.')

print('Setting up PostGIS...', end='')
try:
    cur.execute('CREATE EXTENSION postgis;')
    conn.commit()
except psycopg2.ProgrammingError as e:
    print(str(e).strip(), end='...')
    print('nothing to do.')
    conn.rollback()
else:
    print('done.')

print('Closing the database connection...', end='')
cur.close()
conn.close()
print('done.')

print('Migrating the database models...')
subprocess.call('src/manage.py migrate', shell=True)

print('Creating a superuser account...')
subprocess.call('src/manage.py createdefaultsuperuser', shell=True)

print('Creating a default dataset...')
subprocess.call('src/manage.py runscript createdefaultdataset', shell=True)
