# Settings for the app
app:
  # HTML Title
  title: San Diego Infrastructure Projects (beta)
  # Header name
  name: San Diego Infrastructure Projects (beta)
  # Meta description that will show up in Google search results
  meta_description: _(This app is intended for the citizens of San Diego to register their support for Capital Improvement Projects)

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: true
  options:
    center:
      lat: 32.8978028 
      lng: -117.1425418
    zoom: 10
    minZoom: 10
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  cpgproject:
    default: blue
    focused: red
    label: _(CPG CIP Projects)
  facilities:
    default: green
    focused: red
    label: _(Building Facility)

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  blue:
    iconUrl: /static/css/images/feature-point.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  red:
    iconUrl: /static/css/images/marker-focused.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: false 
  add_button_label: _(Add a Place)
  action_text: _(added)
  title: _(Tell us more...)
  action_text: _(created)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)
  items:
    - prompt: _(Location Name)
      type: text
      name: name
      attrs:
        - key: placeholder
          value: _(Location Name)
        - key: size
          value: 30
    - prompt: _(Location Type)
      type: select
      options:
        - label: _(CIP Project)
          value: cpgproject
        - label: _(Facilities)
          value: facilities
      name: location_type
    - prompt: _(Image)
      inputfile_label: _(Add an Image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30
    - prompt: _(Council District)
      label: _(District)
      type: textarea
      name: district
      optional: true
      attrs:
        - key: placeholder
          value: _(District...)
    - prompt: _(Community Planning Group)
      label: _(Community Planning Group)
      type: textarea
      name: cpg
      optional: true
      attrs:
        - key: placeholder
          value: _(Community Planning Group...)
    - prompt: _(Neighborhood)
      label: _(Neighborhood)
      type: textarea
      name: neighborhood
      optional: true
      attrs:
        - key: placeholder
          value: _(Neighborhood...)
    - prompt: _(General Location)
      label: _(General Location)
      type: textarea
      name: general_location 
      optional: true
      attrs:
        - key: placeholder
          value: _(General Location...)
    - prompt: _(Description)
      label: _(Description)
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(Description...)
    - prompt: _(Purpose)
      label: _(Purpose)
      type: textarea
      name: purpose
      optional: true
      attrs:
        - key: placeholder
          value: _(Purpose...)
    - prompt: _(Urgency)
      label: _(Urgency)
      type: textarea
      name: urgency 
      optional: true
      attrs:
        - key: placeholder
          value: _(Urgency...)

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support This!)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: true

  - title: _(Feedback)
    external: true
    url: https://c4sd.uservoice.com/forums/199107-general 
