# Admin represents the user account for users who can access the Admin section.
# Admins have a level. Currently, level 100 makes an admin a "superadmin," who
# can edit sitewide options and create other Admins. Regular admins have access
# to modify the submitted content, such as FeaturePoints and Comments, and to
# create Pages. 
# An initial admin is generated by running `rake db:seed` so that you can sign
# in to the admin section quickly (see db/seeds.rb for the account info, or to 
# change the default account info), but be certain to change the default admin
# account once you log in, if you're using the info that's in seed.rb.

class Admin < ActiveRecord::Base
  cattr_accessor :current_admin # for setting author in rails_admin
  
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
  
  has_many :pages, :foreign_key => :author_id, :inverse_of => :author
  
  def level
    read_attribute(:level) || 0
  end
  
  def role?(rolename)
    case rolename
    when :superadmin
      return level >= 100
    else
      return false
    end
  end
end