# Settings for the app
app:
  # HTML Title
  title: San Diego Infrastructure Projects (beta)
  # Header name
  name: San Diego Infrastructure Projects (beta)
  # Meta description that will show up in Google search results
  meta_description: _(This app is intended for the citizens of San Diego to register their support for Capital Improvement Projects)

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: true
  options:
    center:
      lat: 32.8978028 
      lng: -117.1425418
    zoom: 10
    minZoom: 10
    maxZoom: 17
  layers:
    - url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  cbaproject:
    label: _(CBA)
    rules:
      - condition: '"{{location_type}}" === "cbaproject"'
        # Display landmarks as icons

        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-0d85e9.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]

        # style:
        #   color: '#0d85e9'
        #   radius: 8
        #   weight: 1
        #   opacity: 0.9
        #   fillOpacity: 0.4
        # focus_style:
        #   color: '#0d85e9'
        #   radius: 16
        #   weight: 1
        #   opacity: 0.9
        #   fillOpacity: 0.4

  cpgproject:
    label: _(CPG)
    rules:
      - condition: '"{{location_type}}" === "cpgproject"'
        # Show parks that are points as icons...

        icon:
          iconUrl: /static/css/images/markers/dot-4bbd45.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-4bbd45.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]

        # ...and parks that are polygons as shapes.

        style:
          color: '#4bbd45'
          radius: 8
          weight: 1
          opacity: 0.9
          fillOpacity: 0.4
        focus_style:
          color: '#4bbd45'
          radius: 16
          weight: 1
          opacity: 0.9
          fillOpacity: 0.4



activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: false
  add_button_label: _(Add a Place)
  action_text: _(added)
  title: _(Tell us more...)
  action_text: _(created)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)
  items:
    - prompt: _(Location Name)
      type: text
      name: name
      attrs:
        - key: placeholder
          value: _(Location Name)
        - key: size
          value: 30
    - prompt: _(Location Type)
      type: select
      options:
        - label: _(CIP Project)
          value: cpgproject
        - label: _(Facilities)
          value: facilities
      name: location_type
    - prompt: _(Image)
      inputfile_label: _(Add an Image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30
    - prompt: _(Council District)
      label: _(District)
      type: textarea
      name: district
      optional: true
      attrs:
        - key: placeholder
          value: _(District...)
    - prompt: _(Community Planning Group)
      label: _(Community Planning Group)
      type: textarea
      name: cpg
      optional: true
      attrs:
        - key: placeholder
          value: _(Community Planning Group...)
    - prompt: _(Neighborhood)
      label: _(Neighborhood)
      type: textarea
      name: neighborhood
      optional: true
      attrs:
        - key: placeholder
          value: _(Neighborhood...)
    - prompt: _(General Location)
      label: _(General Location)
      type: textarea
      name: general_location 
      optional: true
      attrs:
        - key: placeholder
          value: _(General Location...)
    - prompt: _(Description)
      label: _(Description)
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(Description...)
    - prompt: _(Purpose)
      label: _(Purpose)
      type: textarea
      name: purpose
      optional: true
      attrs:
        - key: placeholder
          value: _(Purpose...)
    - prompt: _(Urgency)
      label: _(Urgency)
      type: textarea
      name: urgency 
      optional: true
      attrs:
        - key: placeholder
          value: _(Urgency...)
    - prompt: _(Location Name)
      type: text
      name: name
      attrs:
        - key: placeholder
          value: _(Location Name)
        - key: size
          value: 30
        - key: required
    - prompt: _(Location Type)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Landmark)
          value: landmark
        - label: _(Park)
          value: park
        - label: _(School)
          value: school
      name: location_type
      attrs:
        - key: required
    - prompt: _(Description)
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(Description...)
    - prompt: _(Image)
      inputfile_label: _(Add an Image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support This!)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: true

  - title: _(Feedback)
    external: true
    url: https://c4sd.uservoice.com/forums/199107-general 

notifications:
  on_new_place: true
  submitter_email_field: private-submitter_email
